all:maths run
maths:maths.c add.c sub.c mul.c div.c
        gcc maths.c add.c sub.c mul.c div.c -o maths
run:
	./math
~                                                                                                                                                                                                          
~ 
